version: 2
updates:
  - package-ecosystem: github-actions
    directory: workflows
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - github-actions