name: Security gate

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  semgrep:
    name: Semgrep
    uses: ./.github/workflows/semgrep.yml

  trivy:
    name: Trivy
    uses: ./.github/workflows/trivy.yml